
function collectTmxFiles(dir) {
	var result  = [];
	var entries = File.directoryEntries(dir, File.AllEntries | File.NoDotAndDotDot);

	for (var i = 0; i < entries.length; i++) {
		var fullPath = dir + "/" + entries[i];
		if (File.directoryEntries(fullPath, File.AllEntries) !== undefined &&
			!entries[i].match(/\.[^/]+$/)) {

			var sub = collectTmxFiles(fullPath);
		for (var j = 0; j < sub.length; j++) result.push(sub[j]);
			} else if (entries[i].match(/\.tmx$/i)) {
				result.push(fullPath);
			}
	}
	return result;
}

/* ── Safe C identifier from a file path ── */
function safeName(filePath) {
	return FileInfo.completeBaseName(filePath)
	.replace(/[^a-zA-Z0-9_]/g, "_");
}

/* ── Main action ── */
var exportAction = tiled.registerAction("ExportAllMapsToC", function() {
	tiled.log("[maps] action triggered");

	var folders = tiled.project.folders;
	tiled.log("[maps] project folders: " + JSON.stringify(folders));

	if (!folders || folders.length === 0) {
		tiled.alert("No project folders found.\nPlease add your maps folder via File > Add Folder to Project.");
		return;
	}


	var tmxFiles = [];
	for (var i = 0; i < folders.length; i++) {
		var found = collectTmxFiles(folders[i]);
		tiled.log("[maps] found in " + folders[i] + ": " + found.length);
		for (var j = 0; j < found.length; j++) tmxFiles.push(found[j]);
	}
	tmxFiles.sort();
	tiled.log("[maps] total: " + tmxFiles.length + " .tmx files");

	if (tmxFiles.length === 0) {
		tiled.alert("No .tmx files found in:\n" + folders.join("\n"));
		return;
	}

	/* Ask where to save */
	var outPath = tiled.promptSaveFile("Save maps.h", "maps.h", "C Header (*.h)");
	if (!outPath) { tiled.log("[maps] cancelled"); return; }


	var maps    = [];
	var maxRows = 0;
	var maxCols = 0;
	var errors  = [];

	for (var f = 0; f < tmxFiles.length; f++) {
		tiled.log("[maps] opening: " + tmxFiles[f]);
		var m = tiled.open(tmxFiles[f]);

		if (!m || !m.isTileMap) {
			var e = tmxFiles[f] + ": failed to open";
			tiled.log("[maps] ERROR " + e);
			errors.push(e);
			if (m) tiled.close(m);
			continue;
		}

		var layer = null;
		for (var i = 0; i < m.layerCount; i++) {
			if (m.layerAt(i).isTileLayer) { layer = m.layerAt(i); break; }
		}
		if (!layer) {
			var e = FileInfo.fileName(tmxFiles[f]) + ": no tile layer";
			tiled.log("[maps] ERROR " + e);
			errors.push(e);
			tiled.close(m);
			continue;
		}

		var rows = layer.height;
		var cols = layer.width;
		var data = [];
		for (var y = 0; y < rows; y++) {
			var row = [];
			for (var x = 0; x < cols; x++)
				row.push(layer.cellAt(x, y).tileId);
			data.push(row);
		}

		maps.push({ name: safeName(tmxFiles[f]), rows: rows, cols: cols, data: data });
		if (rows > maxRows) maxRows = rows;
		if (cols > maxCols) maxCols = cols;
		tiled.log("[maps] level " + (maps.length-1) + ": " + maps[maps.length-1].name + " (" + rows + "x" + cols + ")");

		tiled.close(m);
	}

	if (maps.length === 0) {
		tiled.alert("No valid maps could be read.\n\n" + errors.join("\n"));
		return;
	}


	var lines = [];
	lines.push("// Auto-generated by Tiled C 3D Array Exporter — DO NOT EDIT");
	lines.push("// " + maps.length + " level(s), max size " + maxRows + " x " + maxCols);
	lines.push("// Layout: maps[level][y][x]  (-1 = empty / padding)");
	lines.push("");
	lines.push("#ifndef MAPS_H");
	lines.push("#define MAPS_H");
	lines.push("");
	lines.push("#define MAP_COUNT  " + maps.length);
	lines.push("#define MAP_ROWS   " + maxRows);
	lines.push("#define MAP_COLS   " + maxCols);
	lines.push("");
	lines.push("// Level index -> name");
	for (var i = 0; i < maps.length; i++)
		lines.push("// [" + i + "]  " + maps[i].name +
		"  (" + maps[i].rows + " x " + maps[i].cols + ")");
	lines.push("");
	lines.push("const char maps[MAP_COUNT][MAP_ROWS][MAP_COLS] = {");

	for (var lvl = 0; lvl < maps.length; lvl++) {
		var m = maps[lvl];
		lines.push("    /* level " + lvl + ": " + m.name + " */");
		lines.push("    {");
		for (var r = 0; r < maxRows; r++) {
			var cells = [];
			for (var c = 0; c < maxCols; c++)
				cells.push((r < m.rows && c < m.cols) ? m.data[r][c] : -1);
			var rowStr = "        { " + cells.join(", ") + " }";
			if (r < maxRows - 1) rowStr += ",";
			lines.push(rowStr);
		}
		lines.push("    }" + (lvl < maps.length - 1 ? "," : ""));
	}

	lines.push("};");
	lines.push("");
	lines.push("#endif /* MAPS_H */");



	var file = new TextFile(outPath, TextFile.WriteOnly);
	file.write(lines.join("\n"));
	file.commit();
	tiled.log("[maps] written: " + outPath);

	var msg = "Exported " + maps.length + " level(s) to:\n" + outPath;
	if (errors.length > 0)
		msg += "\n\nSkipped " + errors.length + " file(s):\n" + errors.join("\n");
	tiled.alert(msg);
});




exportAction.text = "Export All Maps to C 3D Array";

tiled.extendMenu("File", [
	{ separator: true },
	{ action: "ExportAllMapsToC" }
]);
